-- Supabase table for lotto draw history

create table if not exists public.lotto_draws (
  id bigint generated by default as identity primary key,
  main_numbers jsonb not null,
  bonus_number int not null,
  created_at timestamptz not null default now()
);

create index if not exists lotto_draws_created_at_idx
on public.lotto_draws (created_at desc);

alter table public.lotto_draws enable row level security;
